repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort

  - repo: https://github.com/myint/rstcheck
    rev: "3f92957478422df87bd730abde66f089cc1ee19b"
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx, rstcheck]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
      - id: rst-backticks

  - repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
      - id: codespell
        files: ".py|.rst|.md|.ipynb"
        args: ["-L hist,whos"]

  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.2.3
    hooks:
      - id: flake8-nb
